### PR TITLE
Ensure AnimationInfo is reset when a game is loaded

### LINKED ISSUE #2149: Items often in the air when return to town
I returned to town and there was the cleaver in the air.
Unfortunately, I was unable to reproduce it.
After reloading the game, it was back on the floor. 

cleaver
I'm really sorry I don't have any useful information. I can only attach the savegame when it already looks normal.
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6644125/single_0.hsv.zip)

### PR DESCRIPTION
**Pull request by obligaron**
Fixes #2149

When loading a game not all members of AnimationInfo gets set explicitly.
But we should ensure they are all set to the default.

### CODE REVIEW

File: Source/loadsave.cpp [hunk 1]
```diff
@@ -337,6 +338,7 @@ static void LoadPlayer(LoadHelper *file, int p)
 	file->skip(4); // Unused
 	player._pgfxnum = file->nextLE<int32_t>();
 	file->skip(4); // Skip pointer pData
+	player.AnimInfo = {};
```
Comment (julealgon) [inline Source/loadsave.cpp:341]: This explains the weird behavior @qndel mentioned not being able to repro with the character, right?

**Review by julealgon — APPROVED** [review]

File: Source/loadsave.cpp (hunk 1 above)
Comment (sumyunggai) [reply Source/loadsave.cpp:341]: I can check if this fixes it for me as well.

Comment (sumyunggai) [reply Source/loadsave.cpp:341]: Fixed my issues

**Comment by Chance4us** [comment]
@obligaron , @julealgon , @sumyunggai , @AJenbo , @qndel Thanks for checking/fixing.
