### PR TITLE
Patch up wrong tree tile near Hive entrance (#6869)

### LINKED ISSUE #6869: [Issue Report]: Tiny graphical glitch in Town by Alien Nest (Hellfire)
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

Low priority. Probably a slip-up from way back when Synergistic did Hellfire.
hellfireblemish

I don't know if this would be bothersome to fix and would require like editing of the town. Maybe a crude fix could be done by just making a custom graphic to cover the erroneous tiles.

### To Reproduce

Open in Hellfire and then look across the river.

### Expected Behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Tully-B**
Hi!

This is my first code commit, fixes #6869.

I patched up the offending tiles in town.cpp. I also tried to fix the neighbouring tiles as the Hellfire team did one ugly job there. I hope it's okay. Let me know if the comments are unnecessary, I wanted to keep the original values there.

nest-entrance-compared

On a related note, there's another faulty tree above the river fork that has its shadow cut-off, but it probably has no correct tiles.

bad_tree

### CODE REVIEW

**Comment by qndel** [comment]
Hi, nice change, things to improve:
atm there's a mix between hex and decimals (I know that's how it was before, but since you are changing it, why not fix it? 😄), use hex for consistency?
Your comment suggests that only one of the changes replaces the tree, what does the rest do? If more than 1 patches the tree up, just make a comment before a whole section patching the tree

File: Source/levels/town.cpp [hunk 1]
```diff
@@ -113,17 +113,17 @@ void TownCloseHive()
...
+	dPiece[84][62] = 0x118; // 0x117
+	dPiece[84][63] = 0x117; // 0x117
+	dPiece[84][64] = 10; // 0x117
+	dPiece[85][60] = 11; // 0x117
+	dPiece[85][61] = 12; // 0x117
+	dPiece[85][62] = 13; // 0x117
+	dPiece[85][63] = 14; // 7
+	dPiece[85][64] = 15; // 7
+	dPiece[86][60] = 16; // 0xd8: used to patch up a tree that has been poorly cutoff by the HF devs
+	dPiece[86][61] = 17; // 0x17
```
Comment (AJenbo) [inline Source/levels/town.cpp:126]: We can dig the old values out of git if it's ever needed.
```suggestion
	dPiece[84][61] = 279;
	dPiece[84][62] = 280;
	dPiece[84][63] = 279;
	dPiece[84][64] = 10;
	dPiece[85][60] = 11;
	dPiece[85][61] = 12;
	dPiece[85][62] = 13;
	dPiece[85][63] = 14;
	dPiece[85][64] = 15;
	dPiece[86][60] = 16;
	dPiece[86][61] = 17;
```

File: Source/levels/town.cpp [hunk 2]
```diff
@@ -316,17 +316,17 @@ void TownOpenHive()
...
```
Comment (AJenbo) [inline Source/levels/town.cpp:329]: All other tools use dec for tiles so lets go with that.
```suggestion
	dPiece[84][61] = 279;
	dPiece[84][62] = 280;
	dPiece[84][63] = 279;
	dPiece[84][64] = 10;
	dPiece[85][60] = 11;
	dPiece[85][61] = 12;
	dPiece[85][62] = 13;
	dPiece[85][63] = 14;
	dPiece[85][64] = 15;
	dPiece[86][60] = 16;
	dPiece[86][61] = 17;
```

**Comment by AJenbo** [comment]
Since it can be a bit hard to spot here are the be fore and after to the area that was changed:

The reason appears to be because the original was using the same tile repeatedly making for a very tiling looking grass patch.

image
