### PR TITLE
🐛 Prevent frame-perfect manipulation of spell being cast

### LINKED ISSUE #2844: Frame-perfect exploit when casting scrolls and staff charges
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?

Vanilla issue. Happens on any DevilutionX build.

**Describe**
The issue described in #792 was caused by incorrectly using `pRSpell` as the variable to match the spells during scroll and staff charge removal. This meant a player could use the pre-hitframe frames in the spell animation to quickly swap from the selection he used before, to a different spell, which would then be used in the scroll/staff charge cleanup.

I've found a variation of that bug where, even with the correct `pSpell` being used, the player is _still_ able to influence the scroll/charge cleanup logic by _immediately_ swapping to a different spell while casting. Instead of having the entire window from cast to hit-frame as before, the window is now what appears to be a single frame, similar to how item dupping was exploited.

I'm currently not sure exactly what is creating this vulnerability but it is a different bug than #792, which is why I'm creating this new issue.

**To Reproduce**
1. Select scroll or staff charge as the readied spell
2. Right click to cast
3. _Immediately_ swap to a spell from a different source than the cast spell (this is important, see below)
4. The spell will be cast, but the scroll won't be removed/staff won't have its charges deducted

**Expected behavior**
The scroll should be removed/staff charge should be deducted according to the precise spell used for the cast and should not be influenced by the readied spell after-the-fact.

**Screenshots**
See #792 as the end result is the same.

**Additional context**
Discovered this while playing around with #792 after chatting with @soundchaser83 about it. Originally I believed the issue was related only to the window between cast and hit frame, but after experimenting more with it it became clear that we were seeing 2 distinct behaviors: I was having a much harder time reproing 792 with a scroll in my belt vs the same scenario with a scroll in my inventory.

From my experiments, what I believe is happening is the inverse of 792: I am somehow "casting a healing scroll", but switching to "firebolt" _before_ the cast takes place. So I get a healing cast from the scroll, ~~but mana is consumed as if I cast a firebolt and the scroll is not cleared~~ this is not correct: mana consumption is actually coming from the _healing spell_. Game is treating the scroll as if it was a learned spell.

I'm not sure if this is related to the fact that "casting" sends a network command, but "switching the readied spell" doesn't, meaning the switch happens instantaneously, while the cast is delayed via the messaging system somehow.

FAKE EDIT: I believe I now fully understand where the exploit is coming from. When the "cast" command is sent (in this case a "CMD_SPELLXY"), the tile coordinates and the spell ID are sent as arguments to the command, _but the spell_type **is not**_. When `CMD_SPELLXY` is processed, the "current spell type" is just read from the player casting the spell:

https://github.com/diasurgical/devilutionX/blob/ce40344ae9f9d457736114358036b707191ff4d3/Source/msg.cpp#L957-L978

->

https://github.com/diasurgical/devilutionX/blob/ce40344ae9f9d457736114358036b707191ff4d3/Source/msg.cpp#L970

This means it is possible to perform a cast and, before the command is processed, swap the readied spell to a spell of a different source (say, instead of a scroll, a spell from the spellbook), which _also changes the spell type on the player_, thus influencing the command. 

From there, the modified spell type is then used in other places, _including scroll/staff removal logic in `UseMana`_:

https://github.com/diasurgical/devilutionX/blob/940a120bf92f44c39229681444150f7fa1866c6b/Source/spells.cpp#L164-L184

This explains why this frame-perfect trick does not work when swapping among the same "category". So, trying to cast a Guardian but exploit the swap to use Firebolt mana will not work since both are of the "spell" category.

### PR DESCRIPTION
**Pull request by julealgon**
This PR changes all spell commands where the spell type was previously being inferred to explicitly pass this value at creation time.

This completely eliminates any possibility of manipulating the spell type between cast and execution and causing undefined behavior (like not consuming scrolls, staff changes, using incorrect mana values, etc).

Fixes #2844

### CODE REVIEW

File: Source/msg.cpp [hunk 1]
```diff
@@ -1094,17 +1096,18 @@ DWORD OnRangedAttackPlayer(TCmd *pCmd, Player &player)
 
 DWORD OnSpellMonster(TCmd *pCmd, Player &player)
 {
-	auto *p = (TCmdParam3 *)pCmd;
+	auto *p = (TCmdParam4 *)pCmd;
 
 	if (gbBufferMsgs != 1 && currlevel == player.plrlevel) {
 		auto spell = static_cast<spell_id>(p->wParam2);
+		auto spellType = static_cast<spell_type>(p->wParam3);
```
Comment (AJenbo) [inline Source/msg.cpp:1103]: I think pulling out the parameters at the start of the process like this gives us a good place to perform input validation in preparation for https://github.com/diasurgical/devilutionX/issues/2641 and https://github.com/diasurgical/devilutionX/issues/2707 :+1:

File: Source/msg.h [hunk 2]
```diff
@@ -165,6 +165,16 @@ struct TCmdLocParam3 {
 	uint16_t wParam3;
 };
 
+struct TCmdLocParam4 {
```
Comment (AJenbo) [inline Source/msg.h:168]: Wow, are you sure the tubes will handle sending 11 bytes in a single message :o

**Review by AJenbo — APPROVED** [review]
Nice work, this feels like the very first step in making the netcode sane.
