### PR TITLE
Fix loading order of poison water palette

### LINKED ISSUE #593: Bad pallet at end of loading poisoned water
**Describe**
When entering the poisoned water level blue colors appear in the image as the screen fades.
[single_0.zip](https://github.com/diasurgical/devilutionX/files/4176447/single_0.zip)

**To Reproduce**
Load attached save game and walk in to the poisoned water level

**Expected behavior**
The colors should persist as the scree fade.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by AJenbo**
Fixes #593

This also fixes the issues with lave/water not animating when behind something that is using transparency

### CODE REVIEW

File: Source/palette.cpp [hunk 1]
```diff
@@ -359,6 +398,7 @@ void palette_update_quest_palette(int n)
 	}
 	ApplyGamma(system_palette, logical_palette, 32);
 	palette_update();
+	GenerateBlendedLookupTable(logical_palette, 1, 31, 32 - n);
```
Comment (AJenbo) [inline Source/palette.cpp:401]:
```suggestion
	GenerateBlendedLookupTable(logical_palette, 1, 31, 32 - n); // Possible optimization would be to only update color 0 as only menus has transparency calves this level

```

File: Source/palette.cpp [hunk 2]
```diff
@@ -359,6 +398,8 @@ void palette_update_quest_palette(int n)
 	}
 	ApplyGamma(system_palette, logical_palette, 32);
 	palette_update();
+	GenerateBlendedLookupTable(logical_palette, 1, 31, 32 - n); // Possible optimization would be to only update color 0 as only menus has transparency calves this level
```
Comment (AJenbo) [inline Source/palette.cpp:401]:
```suggestion
	GenerateBlendedLookupTable(logical_palette, 1, 31, 32 - n); // Possible optimization would be to only update color 0 as only the UI can overlap with transparency in this quest
```

**Review by FluffyQuack — COMMENTED** [review]
I have looked at these changes and they have attained the Fluffy stamp of approval! I do not see any indication that they break the rendering of cows, which is the most important of all things.
