### PR TITLE
Keymapper: fix being able to save/load in multiplayer and actions working while entering a message

### LINKED ISSUE #2008: Quick save and quick load hotkeys functional in multiplayer games
**Important information**
Windows 10 x64 Build / Compiled commit 1c77a22735d87078d7810d4044be30c1e3942f90

**Describe**
The hotkeys for quicksave and quickload (default F2 and F3, respectively) work in Multiplayer, when it should only work in Single Player. This may lead to a loss of progress for a character and a potential crash.

**To Reproduce**
1. Start a Multiplayer game with any character.
2. Press the quick save hotkey.
3. Press the quick load hotkey.
4. Character will be reloaded to the state when the quicksave was performed.

**Expected behavior**
Multiplayer games should not have quick save nor quick load enabled. Single Player games should have quick save and quick load enabled.

**Additional context**
If the quick save button was not pressed at any point in the game, but the quick load button is pressed, the game will crash.

### LINKED ISSUE #2069: Hotkeys working while typie msg ingame
When you press Enter and type the message ingame hotkeys assigned to letters C I B S Q are working.

### PR DESCRIPTION
**Pull request by Jmgr**
Fixes #2008
Fixes #2069

### CODE REVIEW

**Review by AJenbo — APPROVED** [review]
Thanks :)

File: Source/diablo.cpp [hunk 1]
```diff
@@ -2237,24 +2254,25 @@ void initKeymapActions()
...
 	    DVL_VK_F2,
 	    [] { gamemenu_save_game(false); },
+	    [&]() { return !gbIsMultiplayer && !isPlayerDead(); },
 	});
 	keymapper.addAction({
 	    "QuickLoad",
 	    DVL_VK_F3,
 	    [] { gamemenu_load_game(false); },
-	    Keymapper::Action::IfDead::Allow,
+	    [&]() { return !gbIsMultiplayer && gbValidSaveFile; },
```
Comment (AJenbo) [inline Source/diablo.cpp:2270]: Technically the check for a save state should be good enough, but probably best to keep both :)
