### PR TITLE
Fix off-by-one in path finding logic

### LINKED ISSUE #7681: [Issue Report]: #7522 breaks auto selecting dungeon objects on touch controls
### Operating System

iOS

### DevilutionX version

Other (please specify version number)

### Describe

When near a dungeon object the auto selecting is not working.

### To Reproduce

Use touch controls
Get near object
See nothing getting selected

### Expected Behavior

Object getting selected

### Additional context

This started occurring after #7522 was merged. Items will auto select only if you stand directly on them.

### PR DESCRIPTION
**Pull request by StephenCWills**
This fixes an issue where items and objects can no longer be interacted with unless the player is on top of them.

In the following conditional statement, the call to `GetDistance()` always returned zero. The reason is that the logic thought that a path of length 1 exceeds the maximum path length of 1 that was passed in via the second argument.

https://github.com/diasurgical/devilutionX/blob/20c0a8dae8b27ac2d5c3e768af2073efa5b18381/Source/controls/plrctrls.cpp#L171-L174

This resolves #7681

### CODE REVIEW

File: Source/engine/path.cpp [hunk 1]
```diff
@@ -162,7 +162,7 @@ int ReconstructPath(const ExploredNodes &explored, PointT dest, int8_t *path, si
 		if (it->second.g == 0) break; // reached start
 		path[len++] = GetPathDirection(it->second.prev, cur);
 		cur = it->second.prev;
-		if (len == maxPathLength) {
+		if (len > maxPathLength) {
```
Comment (glebm) [inline Source/engine/path.cpp:165]: `len` here is the number of steps rather than positions, so if it's 1 that's exactly 1 step 🤔

**Comment by Trihedraf** [comment]
That does fix it in game. But now the tests are broken 🫠

**Comment by glebm** [comment]
The failing test says:

```c++
	// Longest possible path is currently 24 steps meaning tiles 24 units away are reachable
	Point startingPosition { 56, 56 };
	CheckPath(startingPosition, startingPosition + Displacement { 24, 24 }, std::vector<std::string>(24, "↘"));

	// But trying to navigate 25 units fails
	CheckPath(startingPosition, startingPosition + Displacement { 25, 25 }, {});
```

However, the longest possible path is actually 25, so I think the test is wrong.

File: Source/engine/path.cpp (hunk 1 above)
Comment (glebm) [reply Source/engine/path.cpp:165]: Ah, nvm, in this branch we set length to 0.

Comment (glebm) [inline Source/engine/path.cpp:165]: It'd be better to keep this check as is but move it to just before where write to `path` to avoid writing OOB.

Comment (StephenCWills) [reply Source/engine/path.cpp]: You are absolutely correct.

**Comment by StephenCWills** [comment]
I kept the monster path length at 25 because I do not think it particularly matters. Assuming the save format supports path lengths of 25, I think it's reasonable to consider this a bugfix.

I restricted the path tests to 24 so we wouldn't have to change the current test suite. It's still a good test to demonstrate we are appropriately failing when we reach the maximum path length.

**Review by Trihedraf — APPROVED** [review]

**Review by AJenbo — APPROVED** [review]

**Comment by ephphatha** [comment]
> The failing test says:
> 
> ```c++
> 	// Longest possible path is currently 24 steps meaning tiles 24 units away are reachable
> 	Point startingPosition { 56, 56 };
> 	CheckPath(startingPosition, startingPosition + Displacement { 24, 24 }, std::vector<std::string>(24, "↘"));
> 
> 	// But trying to navigate 25 units fails
> 	CheckPath(startingPosition, startingPosition + Displacement { 25, 25 }, {});
> ```
> 
> However, the longest possible path is actually 25, so I think the test is wrong (or we can reduce the maximum path length for monsters to 24, I think that might be closer to previous behaviour)

This was a flaw in the vanilla pathfinding code. The array that stored pathfinding steps had room for 25 entries, but vanilla logic would never use the final entry. https://github.com/diasurgical/devilution/blob/6b7135cec37e9cf0f6740d7e1a1ec880f89e73ff/Source/path.cpp#L78 should've been <= instead to allow for up to 25 steps instead of limiting to 24 or fewer. The test was set up to document that restriction but now that it's been fixed changing the test is fine.
