### PR TITLE
Fixes spawned items from Zhar and Gharbard

### LINKED ISSUE #5979: Zhar's first book does not sync when dropped
When player 1 talks to Zhar the dropped book cannot be picked up by player 2

### PR DESCRIPTION
**Pull request by obligaron**
Fixes #5979

Notes

- In master spawning logic for both happens in `MonsterTalk` and this runs for both clients
- But the spawning logic uses `CMD_DROPITEM` that should only be send by one player (the "source" of the action)
- Also the used seed for the spawned items can differ between clients (and therefore also the item)
- This PR uses only `CMD_SPAWNITEM` that doesn't depend on the same logic (and same seed) is executed on both clients
- `CMD_SPAWNITEM` is only send by the player that talks to the quest monster
- The item spawning logic should be refactored at some point (we currently have `sendmsg`, `delta` and now `spawn`)

### CODE REVIEW

File: Source/items.cpp [hunk 1]
```diff
@@ -3226,7 +3228,7 @@ Item *SpawnUnique(_unique_items uid, Point position, bool sendmsg /*= true*/)
 	return &item;
 }
 
-void SpawnItem(Monster &monster, Point position, bool sendmsg)
+void SpawnItem(Monster &monster, Point position, bool sendmsg, bool spawn /*= false*/)
```
Comment (AJenbo) [inline Source/items.cpp:3231]: SpawnItem() having an option not to spawn confused me, but it's only related to spawning on other clients now that i read it while awake.

**Review by AJenbo — APPROVED** [review]

File: Source/items.cpp (hunk 1 above)
Comment (obligaron) [reply Source/items.cpp:3231]: It's still confusing that's why I mentioned a possible refactoring in the notes 🙂
