### PR TITLE
64bit Compatible Saves

### LINKED ISSUE #118: Broken savegame
For some reason my savegame got damaged. The file is attached and when loading the game crashes. The question now is if it is possible to find the reason and maybe also to repair the it?
[single_3.sv.zip](https://github.com/diasurgical/devilutionX/files/3213446/single_3.sv.zip)

### PR DESCRIPTION
**Pull request by sweetgiorni**
Instead of copying entire structures with pointer members in them, individually copy each member and skip the pointers so the save file size is consistent across architectures.

In my tests, this change makes authentic x32 saves, devilutionx x32 saves, and devilutionx x64 saves all compatible with each other. 

Any devilutionx x64 saves created before this change will be permanently broken (since they copied 64 bit pointer members into save buffer). 

Closes #118, #53

### CODE REVIEW

File: structs.h [hunk 1]
```diff
@@ -90,6 +92,7 @@ typedef struct ItemGetRecordStruct {
 	unsigned int dwTimestamp;
 } ItemGetRecordStruct;
 
+#pragma pack(push, 4)
```
Comment (AJenbo) [inline structs.h]: Is it still needed to change the default packing now that we are copying the individual structure members?

File: Source/loadsave.cpp [hunk 2]
```diff
@@ -1,700 +1,1644 @@
...
-	for (i = 0; i < MAX_PLRS; i++) {
-		if (plr[i].plractive && currlevel == plr[i].plrlevel)
-			LightList[plr[i]._plid]._lunflag = 1;
-	}
-
-	mem_free_dbg(LoadBuff);
-}
-
-DEVILUTION_END_NAMESPACE
+#include "diablo.h"
```
Comment (AJenbo) [inline Source/loadsave.cpp]: Looks like the file has been reformatted (\n vs \n\r) causing a lot of diff in this PR.

File: Source/loadsave.cpp [hunk 3]
```diff
@@ -1,700 +1,1644 @@
...
+	if (*tbuff++ == TRUE)
+		return TRUE;
+	else
+		return FALSE;
+}
+
+void CopyInt(const void *src, void *dst)
+{
+	memcpy(dst, src, 4);
+	tbuff += 4;
```
Comment (AJenbo) [inline Source/loadsave.cpp]: It feels a bit odd that the function takes `src` yet operates on `tbuff`, probably better to just use `tbuff` directly in both places. Also does it have any benifits over using the existing `ILoad()`?

File: Source/loadsave.cpp (hunk 2 above)
Comment (sweetgiorni) [reply Source/loadsave.cpp]: Oops, fixed.

File: Source/loadsave.cpp (hunk 3 above)
Comment (sweetgiorni) [reply Source/loadsave.cpp]: I was initially trying to use a single function to pack and unpack these structs, so I wrote Copy*() functions that can be used for both packing and unpacking, automatically incrementing tbuff. 
In the case of packing, the dst pointer (tbuff) would need to be incremented, and in the case of unpacking, the source pointer (tbuff) would need to be incremented. But since the function is more generic than ILoad(), it can't know which pointer to increment without passing it extra args. So this keeps a single function for packing and unpacking Ints from the MPQ save data while still keeping a light function signature.

File: Source/loadsave.h [hunk 4]
```diff
@@ -9,12 +9,17 @@ char BLoad();
...
+void SaveItem(ItemStruct *pItem);
+void SaveItems(ItemStruct *pItem, const int n);
+
 void LoadPlayer(int i);
 void LoadMonster(int i);
 void LoadMissile(int i);
 void LoadObject(int i);
-void LoadItem(int i);
-void LoadPremium(int i);
+void LoadItem(int t);
```
Comment (AJenbo) [inline Source/loadsave.h]:
```suggestion
void LoadItem(int i);
```

File: Source/loadsave.h [hunk 5]
```diff
@@ -9,12 +9,17 @@ char BLoad();
...
+void LoadPremium(int t);
```
Comment (AJenbo) [inline Source/loadsave.h]:
```suggestion
void LoadPremium(int i);
```

File: structs.h (hunk 1 above)
Comment (sweetgiorni) [reply structs.h]: Fixed - any save-related structs that don't have pointer members are still loaded with a single memcpy and so pragma pack is required, but it has been removed from structs that don't need it

File: Source/loadsave.cpp [hunk 6]
```diff
@@ -207,42 +207,825 @@ BOOL OLoad()
...
+
+	CopyShorts(tbuff, 8, &pPlayer->wReserved);
+
+	CopyInt(tbuff, &pPlayer->pDiabloKillLevel);
+	CopyInts(tbuff, 7, &pPlayer->dwReserved);
+
+	// Omit 10 pointers
+}
+
+void SavePlayer(int i)
```
Comment (AJenbo) [inline Source/loadsave.cpp]: Could you move SavePlayer and SaveItem down to SaveMonster so that they align with the original code.

File: structs.h [hunk 7]
```diff
@@ -1314,21 +1321,21 @@ typedef struct _SNETUIDATA {
...
-	void(* selectedcallback)();
-	void(* messageboxcallback)();
-	void(* soundcallback)();
-	void(* statuscallback)();
-	void(* getdatacallback)();
-	void(* categorycallback)();
-	void(* categorylistcallback)();
-	void(* newaccountcallback)();
-	void(* profilecallback)();
+	void (*artcallback)();
```
Comment (AJenbo) [inline structs.h]: A bit of reformatting happening here also, please keep to the format defined by .clang-format.

File: structs.h [hunk 8]
```diff
@@ -1,3 +1,5 @@
+#pragma once
```
Comment (AJenbo) [inline structs.h]: Probably we should apply this upstream.

File: structs.h (hunk 7 above)
Comment (sweetgiorni) [reply structs.h]: Looks like this formatting was done by .clang-format... was it wrong in the first place or is my formatter screwed up?

Comment (AJenbo) [reply structs.h]: Oh your right, it's not been formatted properly. If it's not a hassle then leave it out since it would be better to fix it upstream in a relevant commit.

Comment (sweetgiorni) [reply structs.h]: Done

File: structs.h (hunk 8 above)
Comment (sweetgiorni) [reply structs.h]: Removed this from this commit

**Comment by Predelnik** [comment]
Since functions are large and require a lot of additional helper functions wouldn't it make sense to move them to a separate file in `SourceX` to avoid a ton of conflicts with possible changes from devilution and just put original ones in `#ifdef` for example?

**Comment by AJenbo** [comment]
@Predelnik I don't expect these functions to change upstream. I also feel we are at the point where we will slowly start to diverge from upstream in order to make the code more robust/portable and less buggy.

File: Source/loadsave.cpp [hunk 9]
```diff
@@ -207,42 +207,537 @@ BOOL OLoad()
 		return FALSE;
 }
 
+void CopyInt(const void *src, void *dst)
```
Comment (Predelnik) [inline Source/loadsave.cpp]: Could we really do `memcpy` here if we're going to support big-endian systems? (#70)
Shouldn't it be implement similar to original `WLoad` then?
If that's the case it probably would not work with `void*`->`void*` interface then unfortunately

Comment (Predelnik) [reply Source/loadsave.cpp]: I would also suggest to use `template`s here, that would make implementation more concise and allow to not hardcode sizes, but this may be done as an improvement later of course.

Comment (AJenbo) [reply Source/loadsave.cpp]: A endian safe implementation would definatly be prefered, but maybe not required initially since the whole engine needs endian work.

**Comment by photodude** [comment]
@sweetgiorni 
Since you said
> Any devilutionx x64 saves created before this change will be permanently broken (since they copied 64 bit pointer members into save buffer).

Would it be possible on the load side to check if it's an old version of the x64 save file with copied 64 bit pointer members in the save buffer, then migrate that file to the new save format proposed here?

**Comment by sweetgiorni** [comment]
@photodude If there were a way to tell if a save is 64 bits, then it would definitely be easy - but I'm not sure if we can deduce that information programmatically. The nature of these save files is really just, "memcpy the structure and hope to god it works". It might be possible to look at the data in the buffer and guess if it's x64, but that's not guaranteed to work every time and will probably just cause more problems.

From another point of view, we want authentic Diablo save files and devilutionx save files to be inter-compatible with both games. By that standard, there is only _one_ save format - the original 32 bit format - and everything else is wrong. I mean, there's a reason CMake warns you that the 64 bit build is experimental :)

One could, however, create a program that will fix the 64 save to use the proper format, but that would be time-consuming (for me at least; someone else may be able to make it very quickly). Probably not worth it for a one-off tool.

**Comment by baosen** [comment]
Hi, after this commit, after saving my game on a 64-bit build using the "Save Game"-button, my game started acting weird. The dungeon lightning suddenly was off (wrong lightning direction, it seems) and I could no longer open those huge white and a little bit yellow sanctuary graveyard chests. After re-loading game, the game runs a little bit, then suddenly crashes and exits.

I've attached 2 logs on this issue, the first one played from the beginning as a rogue and the second one played from the beginning as a warrior:

[diablo_crash_rogue.log](https://github.com/diasurgical/devilutionX/files/3387735/diablo_crash_rogue.log)
[diablo_warrior_crash.log](https://github.com/diasurgical/devilutionX/files/3387734/diablo_warrior_crash.log)

Before this commit, playing as a Warrior on a 64-bit build worked fine, both loading and saving the game :S.

I'm playing this game on a 64-bit Ubuntu 19.04 using g++ (Ubuntu 8.3.0-6ubuntu1) 8.3.0 to compile the game.

**Comment by Predelnik** [comment]
First line in `SaveObjects`
```cpp
CopyInt(tbuff, &pObject->_otype);
```
should be 
```cpp
CopyInt(&pObject->_otype, tbuff);
```
right?

**Comment by baosen** [comment]
@Predelnik 

Wow, you found the bug :).  Correcting it the way you described it fixes the issue :+1:

**Comment by qndel** [comment]
I've heard farmers are reporting unusually high yields from crops in Predelnik's home town because he caught all the bugs!

**Comment by scresante** [comment]
@Predelnik  Yep that argument swap was the problem. I see you already submitted the PR. **Thanks alot!!**

**Comment by AJenbo** [comment]
Thanks everyone for testing and reporting, I have been to swamped at work and in life to do so lately
