### PR TITLE
Remove frame queue exceptions from the network layer

### LINKED ISSUE #6602: Remove exceptions from network code
Network code is the only place in the codebase where we use exceptions.

Removing exceptions from network code will pave a path for network support on platforms that do not support exceptions (e.g. nxdk). I also think it will make the code easier to follow.

Exceptions can be replaced with `tl::expected`.

ASIO can be configured to avoid exceptions, we just need to provide a custom "throw" implementation. More information from @StephenCWills:

> Found some info for building ASIO without exceptions.
> https://github.com/chriskohlhoff/asio/issues/302#issuecomment-386375713
> 
> Here's an option I thought of based on your work in this PR. Something like...
> 
> ```c++
> tl::expected<void, PacketError> tcp_client::poll()
> {
> 	while (ioc.poll_one() > 0) {
> 		if (ioHandlerError != nullptr)
> 			return t1::make_unexpected(*ioHandlerError);
> 	}
> }
> ```

### PR DESCRIPTION
**Pull request by StephenCWills**
Another step on the journey to solving #6602. This eliminates the last of the exceptions used on the TCP side, and eliminates one call to `ABORT()`, albeit one that I don't think we've ever actually encountered. ZT still has `protocol_exception`, but that appears to be all that's left after this.

### CODE REVIEW

File: Source/dvlnet/base.cpp [hunk 1]
```diff
@@ -470,7 +477,10 @@ bool base::SNetDropPlayer(int playerid, uint32_t flags)
 		LogError("make_packet: {}", pkt.error().what());
 		return false;
 	}
-	send(**pkt);
+	if (tl::expected<void, PacketError> result = send(**pkt); !result.has_value()) {
```
Comment (AJenbo) [inline Source/dvlnet/base.cpp:480]: Nit: personally I prefer this style
```suggestion
	tl::expected<void, PacketError> result = send(**pkt);
	if (!result.has_value()) {
```

Comment (StephenCWills) [reply Source/dvlnet/base.cpp]: No objections here.

**Review by AJenbo — APPROVED** [review]
