### PR TITLE
[Bugfix] Update players directions on joining

### LINKED ISSUE #4154: Player direction isn't synced on joining the game
**Important information**
Windows 10 / compiled 3636df44b7a28332cc5c5a8e9187ac7eab886a6a

**Describe**
Character rotated in the wrong direction.

**To Reproduce**
Create a game
Move the character so it's facing a direction different than south
Join the game with another character
It sees the first one facing south

**Expected behavior**
Direction is synced on joining properly.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by yuripourre**
Update players' directions on joining a multiplayer game.

Closes #4154

### CODE REVIEW

File: Source/pack.cpp [hunk 1]
```diff
@@ -489,9 +490,11 @@ bool UnPackNetPlayer(const PlayerNetPack &packed, Player &player)
 
 	ValidateField(packed._pNumInv, packed._pNumInv <= InventoryGridCells);
 
+	ValidateField(packed.pdir, packed.pdir <= static_cast<uint8_t>(Direction::NoDirection));
```
Comment (StephenCWills) [inline Source/pack.cpp]: Is `Direction::NoDirection` valid for `pdir`? Seems like you might be able to induce a crash by making a remote client attempt to render your animation with `Direction::NoDirection`.

File: Source/multi.cpp [hunk 2]
```diff
@@ -724,6 +725,13 @@ void ProcessGameMessagePackets()
 			player._pBaseStr = pkt->bstr;
 			player._pBaseMag = pkt->bmag;
 			player._pBaseDex = pkt->bdex;
+			
+			const Direction newDir = static_cast<Direction>(pkt->pdir);
```
Comment (StephenCWills) [inline Source/multi.cpp]: This value came from a remote client! It has to be validated before we can use it!

**Review by StephenCWills — APPROVED** [review]
Looks great. Can you run clang-format? Looks like there's a formatting error in `multi.cpp`.

**Comment by yuripourre** [comment]
@StephenCWills Done! Thank you so much for reviewing!
