### PR TITLE
Respect hell and hellfire color maps for fully lit and fully dark tiles

### LINKED ISSUE #6535: [Issue Report]: Flickering graphics issue walking underneath animated ceiling tiles
### Operating System

Windows x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

Using latest master [52b806c]

https://github.com/diasurgical/devilutionX/assets/57089001/e80fdf66-6f7a-44cf-997f-4133d66b202e

### To Reproduce

Walk under animated ceiling tiles

### Expected Behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by obligaron**
Fixes #6535

## Background
- The renderer has a optimization for fully lit and fully dark tiles.
  - For fully lit tiles (light table index 0) the color map is ignored and a simple copy of the pixels is made
  - For fully dark tiles (light table index 15) the color map is ignored and all pixels are filled with black.
- This optimization assumes that the color map always maps to the same color (fully lit) or maps always maps to black (fully dark). This is not true.
  - Hell levels have a color map for fully lit tiles to support the ceiling animation.
  - Hellfire levels there do not have a fully dark color map.
- In #6535 one ceiling tile has a dLight value of 0 (fully lit).
  - This happens more often in devilutionX, because the light is updated more often since b7424a0068f59cfa253c959dd27accbdd317156a.
  - The bug is more visible when + light radius items are equipped.

## Changes
- Added a helper (`IsFullyDark`/`IsFullyLit`) to check if the optimization can be used.
- Don't use incompatible optimizations for the affected levels.
- Added an assert to check if the optimizations are correctly enabled/disabled.

## Notes
- We can change the way hellfire levels are handled. Currently they mostly use the color `1` for completely dark tiles. We could change this to pure black (`0`) and still use the optimization.

### CODE REVIEW

File: Source/lighting.cpp [hunk 1]
```diff
@@ -361,14 +365,19 @@ void MakeLightTable()
...
 	} else if (IsAnyOf(leveltype, DTYPE_NEST, DTYPE_CRYPT)) {
 		// Make the lava fully bright
 		for (auto &lightTable : LightTables)
 			std::iota(lightTable.begin(), lightTable.begin() + 16, uint8_t { 0 });
 		LightTables[15][0] = 0;
 		std::fill_n(LightTables[15].begin() + 1, 15, 1);
+		FullyDarkLightTable = nullptr; // Tiles in Hellfire levels are never completely black
 	}
 
+	assert((FullyLitLightTable != nullptr) == (LightTables[0][0] == 0 && std::adjacent_find(LightTables[0].begin(), LightTables[0].end() - 1, [](auto x, auto y) { return (x + 1) != y; }) == LightTables[0].end() - 1));
```
Comment (glebm) [inline Source/lighting.cpp:378]: Can you please add a comment about what these asserts are testing

**Review by glebm — APPROVED** [review]

**Review by AJenbo — APPROVED** [review]
I didn't think that was actually solvable as I though it was related to the pixels which where incorrectly encoded in the tiles. Nice work :)

**Comment by AJenbo** [comment]
@glebm oh, sorry I see I overlapped with  your comment/review

File: Source/lighting.cpp (hunk 1 above)
Comment (obligaron) [reply Source/lighting.cpp:378]: I opened #7168 for it 🙂

**Comment by obligaron** [comment]
> I didn't think that was actually solvable as I though it was related to the pixels which where incorrectly encoded in the tiles. Nice work :)

That was my first impression too, but then I discovered that the older version didn't have this problem. And so my chase down the rabbit hole began. 😁
