### PR TITLE
"Dead Pixels" when trying to equip item

### LINKED ISSUE #1962: "Dead Pixels" when trying to equip item
**Important information**
Master branch on 4cd1fd9b727e5ec059b447d674fa7e825e90c4a2

**Describe**
When trying to equip an item in the exact center of the slot it doesn't allow it to equip. Moving one pixel off center and it equips as expected.

**To Reproduce**
1. Create a new game as rogue
2. Click on the equipped weapon
3. Move the mouse cursor so that the equipment is in the exact center (it will not do anything)
4. Move the mouse cursor one pixel on any direction (it will equip correctly)

**Additional context**
_Originally posted by @glebm in https://github.com/diasurgical/devilutionX/issues/1885#issuecomment-840274498_

### PR DESCRIPTION
**Pull request by stefanmielke**
One pixel was not being calculated on the X axis when trying to find for an inventory slot to put the item.

Closes #1962 and should fix controller not being able to equip when on low resolutions.

@AJenbo @glebm

### CODE REVIEW

**Review by glebm — APPROVED** [review]

File: Source/inv.cpp [hunk 1]
```diff
@@ -869,7 +869,7 @@ void CheckInvPaste(int pnum, int mx, int my)
 			yo = PANEL_TOP;
 		}
 
-		if (i >= InvRect[r].X + xo && i < InvRect[r].X + xo + INV_SLOT_SIZE_PX) {
+		if (i >= InvRect[r].X + xo && i <= InvRect[r].X + xo + INV_SLOT_SIZE_PX) {
 			if (j >= InvRect[r].Y + yo - INV_SLOT_SIZE_PX - 1 && j < InvRect[r].Y + yo) {
```
Comment (glebm) [inline Source/inv.cpp:873]: Should the same be done for the Y coordinate?

**Comment by glebm** [comment]
So this allows the middle of the cursor to be 1px beyond the right edge of the tile?
Seems weird that this is the fix but I don't really know how this works :shrug:

File: Source/inv.cpp (hunk 1 above)
Comment (stefanmielke) [reply Source/inv.cpp:873]: I couldn't reproduce the same problem after applying the fix for X. I could do a few more tests if we want to be sure.

**Comment by stefanmielke** [comment]
> So this allows the middle of the cursor to be 1px beyond the right edge of the tile?
> Seems weird that this is the fix but I don't really know how this works shrug

Basically mouseX was 1005, but it was only checking up to 1004 on the first slot, and starting from 1006 on the one right next to it.

**Review by glebm — COMMENTED** [review]
Perhaps a slightly cleaner fix might be to change the calculation of the middle pixel of the cursor to:

```c++
i = mx + (icursW - 1) / 2;
j = my + (icursH - 1) / 2;
```

Imagine a 2px cursor. We could consider either the left or the right pixel as the "middle".

Previously it was the right pixel, with this change it'd be the left pixel

**Comment by glebm** [comment]
> Basically mouseX was 1005, but it was only checking up to 1004 on the first slot, and starting from 1006 on the one right next to it. My guess is that it was discarding the border.

Ah, nevermind my previous comment then!

File: Source/inv.cpp (hunk 1 above)
Comment (AJenbo) [reply Source/inv.cpp:873]: im gussing its already offset via -1
