### PR TITLE
Sync loading of dLight and automap data

### LINKED ISSUE #2267: dLight array is saved/loaded twice
dLight array is saved/loaded twice

See LoadGame/SaveGameData

https://github.com/diasurgical/devilutionX/blob/master/Source/loadsave.cpp#L1194
https://github.com/diasurgical/devilutionX/blob/master/Source/loadsave.cpp#L1224

https://github.com/diasurgical/devilutionX/blob/master/Source/loadsave.cpp#L1960
https://github.com/diasurgical/devilutionX/blob/master/Source/loadsave.cpp#L1990

### LINKED ISSUE #5298: Light data can bug out when loading at high resolutions
### Operating System

Windows x64

### DevilutionX version

Other (please specify version number)

### Describe

lji1
[single_3.zip](https://github.com/diasurgical/devilutionX/files/9438859/single_3.zip)

### To Reproduce

1. Load attached savefile at 1600x900
2. See light where darkness should be.

### Expected Behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AJenbo**
Fixes #5298
Fixes #2267

Previously correction of dLight and automap data was only corrected when loading a non-town level, not when loading a save state or town.

This also fully skips loading of dLight data for a bit faster loading.

### CODE REVIEW

File: Source/loadsave.cpp [hunk 1]
```diff
@@ -2201,19 +2198,24 @@ void LoadGame(bool firstflag)
...
+			for (int i = 0; i < DMAXX; i++) { // NOLINT(modernize-loop-convert)
+				const auto automapView = static_cast<MapExplorationType>(file.NextLE<uint8_t>());
+				AutomapView[i][j] = automapView == MAP_EXP_OLD ? MAP_EXP_SELF : automapView;
+			}
 		}
 		file.Skip(MAXDUNX * MAXDUNY); // dMissile
+
+		// No need to load dLight, we can recreate it accurately from LightList
+		memcpy(dLight, dPreLight, sizeof(dLight));                                     // resets the light on entering a level to get rid of incorrect light
+		ChangeLightXY(Players[MyPlayerId].lightId, Players[MyPlayerId].position.tile); // forces player light refresh
```
Comment (StephenCWills) [inline Source/loadsave.cpp:2216]:
```suggestion
		// No need to load dLight, we can recreate it accurately from LightList
		memcpy(dLight, dPreLight, sizeof(dLight));               // resets the light on entering a level to get rid of incorrect light
		ChangeLightXY(myPlayer.lightId, myPlayer.position.tile); // forces player light refresh
```

**Review by StephenCWills — DISMISSED** [review]

**Review by StephenCWills — APPROVED** [review]
