### PR TITLE
Palette KD-tree: Fix compilation speed

### LINKED ISSUE #8135: palette_kd_tree.hpp: Slow compilation when debug info is enabled
When using a build with debug information enabled (e.g. `RelWithDebInfo`), that file is very slow to compile.

gcc version:
```
gcc (Ubuntu 14.2.0-19ubuntu2) 14.2.0
```

Compiling `palette_blending_benchmark` with `-ftime-report`:

```
grep palette_blending_benchmark.cpp build-reld/compile_commands.json
# then run the command above with `-ftime-report`
```

```
Time variable                                   usr           sys          wall           GGC
 phase setup                        :   0.00 (  0%)   0.00 (  0%)   0.00 (  0%)  1783k (  1%)
 phase parsing                      :   1.28 (  0%)   0.93 ( 48%)   2.22 (  0%)   233M ( 79%)
 phase lang. deferred               :   0.12 (  0%)   0.05 (  3%)   0.17 (  0%)    21M (  7%)
 phase opt and generate             :1215.95 (100%)   0.95 ( 49%)1217.09 (100%)    39M ( 13%)
 phase last asm                     :   0.02 (  0%)   0.00 (  0%)   0.02 (  0%)  1017k (  0%)
 |name lookup                       :   0.28 (  0%)   0.18 (  9%)   0.37 (  0%)  5933k (  2%)
 |overload resolution               :   0.11 (  0%)   0.06 (  3%)   0.16 (  0%)    17M (  6%)
 dump files                         :   0.03 (  0%)   0.00 (  0%)   0.03 (  0%)     0  (  0%)
 callgraph construction             :   0.03 (  0%)   0.00 (  0%)   0.03 (  0%)  7300k (  2%)
 callgraph optimization             :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)  3472  (  0%)
 callgraph functions expansion      :1215.81 (100%)   0.89 ( 46%)1216.90 (100%)    22M (  7%)
 callgraph ipa passes               :   0.07 (  0%)   0.03 (  2%)   0.11 (  0%)  5195k (  2%)
 ipa cp                             :   0.00 (  0%)   0.00 (  0%)   0.01 (  0%)    73k (  0%)
 ipa inlining heuristics            :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)   578k (  0%)
 ipa profile                        :   0.00 (  0%)   0.00 (  0%)   0.01 (  0%)     0  (  0%)
 ipa points-to                      :   0.01 (  0%)   0.01 (  1%)   0.00 (  0%)    28k (  0%)
 ipa free lang data                 :   0.00 (  0%)   0.00 (  0%)   0.01 (  0%)     0  (  0%)
 cfg cleanup                        :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)   205k (  0%)
 df reaching defs                   :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)     0  (  0%)
 df live regs                       :   0.01 (  0%)   0.00 (  0%)   0.02 (  0%)  6112  (  0%)
 df live&initialized regs           :   0.03 (  0%)   0.00 (  0%)   0.02 (  0%)     0  (  0%)
 df use-def / def-use chains        :   0.00 (  0%)   0.00 (  0%)   0.01 (  0%)     0  (  0%)
 df reg dead/unused notes           :   0.01 (  0%)   0.00 (  0%)   0.01 (  0%)   167k (  0%)
 alias analysis                     :   0.00 (  0%)   0.00 (  0%)   0.01 (  0%)   484k (  0%)
 alias stmt walking                 :   0.00 (  0%)   0.00 (  0%)   0.02 (  0%)    27k (  0%)
 preprocessing                      :   0.13 (  0%)   0.25 ( 13%)   0.39 (  0%)    24M (  8%)
 parser (global)                    :   0.35 (  0%)   0.33 ( 17%)   0.71 (  0%)    71M ( 24%)
 parser struct body                 :   0.06 (  0%)   0.01 (  1%)   0.17 (  0%)    20M (  7%)
 parser enumerator list             :   0.02 (  0%)   0.00 (  0%)   0.00 (  0%)   918k (  0%)
 parser function body               :   0.02 (  0%)   0.02 (  1%)   0.06 (  0%)  2747k (  1%)
 parser inl. func. body             :   0.37 (  0%)   0.16 (  8%)   0.38 (  0%)    44M ( 15%)
 parser inl. meth. body             :   0.14 (  0%)   0.04 (  2%)   0.15 (  0%)    30M ( 10%)
 template instantiation             :   0.21 (  0%)   0.16 (  8%)   0.43 (  0%)    42M ( 14%)
 constant expression evaluation     :   0.08 (  0%)   0.01 (  1%)   0.05 (  0%)  1424k (  0%)
 constraint normalization           :   0.00 (  0%)   0.00 (  0%)   0.01 (  0%)   390k (  0%)
 constraint satisfaction            :   0.00 (  0%)   0.00 (  0%)   0.01 (  0%)  1007k (  0%)
 integration                        :   0.01 (  0%)   0.01 (  1%)   0.06 (  0%)  4015k (  1%)
 tree gimplify                      :   0.00 (  0%)   0.01 (  1%)   0.00 (  0%)  1078k (  0%)
 tree CFG cleanup                   :   0.00 (  0%)   0.01 (  1%)   0.01 (  0%)   148k (  0%)
 tree VRP                           :   0.03 (  0%)   0.00 (  0%)   0.03 (  0%)   220k (  0%)
 tree Early VRP                     :   0.00 (  0%)   0.01 (  1%)   0.02 (  0%)   339k (  0%)
 tree copy propagation              :   0.00 (  0%)   0.00 (  0%)   0.01 (  0%)    21k (  0%)
 tree PTA                           :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)    85k (  0%)
 tree SSA rewrite                   :   0.00 (  0%)   0.01 (  1%)   0.00 (  0%)   278k (  0%)
 tree operand scan                  :   0.01 (  0%)   0.00 (  0%)   0.01 (  0%)  1159k (  0%)
 dominator optimization             :   0.06 (  0%)   0.00 (  0%)   0.04 (  0%)   267k (  0%)
 backwards jump threading           :   0.05 (  0%)   0.00 (  0%)   0.06 (  0%)   177k (  0%)
 tree SRA                           :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)   103k (  0%)
 tree CCP                           :   0.02 (  0%)   0.00 (  0%)   0.03 (  0%)    94k (  0%)
 tree PRE                           :   0.04 (  0%)   0.00 (  0%)   0.04 (  0%)   497k (  0%)
 tree FRE                           :   0.01 (  0%)   0.00 (  0%)   0.01 (  0%)   208k (  0%)
 tree canonical iv                  :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)    82k (  0%)
 complete unrolling                 :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)   470k (  0%)
 tree vectorization                 :   0.01 (  0%)   0.00 (  0%)   0.02 (  0%)  3568k (  1%)
 tree slp vectorization             :   0.00 (  0%)   0.00 (  0%)   0.01 (  0%)   788k (  0%)
 tree iv optimization               :   0.01 (  0%)   0.00 (  0%)   0.01 (  0%)   581k (  0%)
 tree copy headers                  :   0.02 (  0%)   0.00 (  0%)   0.01 (  0%)   295k (  0%)
 tree modref                        :   0.00 (  0%)   0.01 (  1%)   0.00 (  0%)   159k (  0%)
 dominance computation              :   0.00 (  0%)   0.00 (  0%)   0.03 (  0%)     0  (  0%)
 expand vars                        :   0.00 (  0%)   0.00 (  0%)   0.01 (  0%)   198k (  0%)
 expand                             :   0.00 (  0%)   0.00 (  0%)   0.00 (  0%)  1843k (  1%)
 CSE                                :   0.02 (  0%)   0.00 (  0%)   0.01 (  0%)    19k (  0%)
 dead code elimination              :   0.00 (  0%)   0.00 (  0%)   0.01 (  0%)     0  (  0%)
 dead store elim1                   :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)   114k (  0%)
 loop init                          :   0.02 (  0%)   0.00 (  0%)   0.00 (  0%)  1197k (  0%)
 loop invariant motion              :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)  3888  (  0%)
 CPROP                              :   0.00 (  0%)   0.00 (  0%)   0.01 (  0%)   365k (  0%)
 combiner                           :   0.01 (  0%)   0.00 (  0%)   0.02 (  0%)   865k (  0%)
 integrated RA                      :   0.03 (  0%)   0.00 (  0%)   0.04 (  0%)  1668k (  1%)
 LRA non-specific                   :   0.00 (  0%)   0.00 (  0%)   0.01 (  0%)    53k (  0%)
 LRA create live ranges             :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)  8904  (  0%)
 reload CSE regs                    :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)   151k (  0%)
 ree                                :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)    23k (  0%)
 if-conversion 2                    :   0.00 (  0%)   0.00 (  0%)   0.01 (  0%)   184  (  0%)
 scheduling 2                       :   0.02 (  0%)   0.00 (  0%)   0.01 (  0%)    59k (  0%)
 shorten branches                   :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)     0  (  0%)
 final                              :   0.01 (  0%)   0.00 (  0%)   0.01 (  0%)  1181k (  0%)
 symout                             :   0.04 (  0%)   0.00 (  0%)   0.05 (  0%)    18M (  6%)
 variable tracking                  :   0.01 (  0%)   0.00 (  0%)   0.03 (  0%)   584k (  0%)
 var-tracking dataflow              :   0.03 (  0%)   0.00 (  0%)   0.03 (  0%)    12k (  0%)
 var-tracking emit                  :   0.02 (  0%)   0.00 (  0%)   0.01 (  0%)   910k (  0%)
 if to switch conversion            :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)    72  (  0%)
 uninit var analysis                :1215.23 (100%)   0.88 ( 46%)1216.29 (100%)   328  (  0%)
 tree loop if-conversion            :   0.00 (  0%)   0.00 (  0%)   0.01 (  0%)   354k (  0%)
 rest of compilation                :   0.01 (  0%)   0.00 (  0%)   0.00 (  0%)    87k (  0%)
 TOTAL                              :1217.37          1.93       1219.50          296M
```

We can see that the time is spent in:

```
phase opt and generate             :1215.95 (100%)   0.95 ( 49%)1217.09 (100%)    39M ( 13%)
callgraph functions expansion      :1215.81 (100%)   0.89 ( 46%)1216.90 (100%)    22M (  7%)
uninit var analysis                :1215.23 (100%)   0.88 ( 46%)1216.29 (100%)   328  (  0%)
```

Perhaps we can restructure the code a bit to make it obvious to the compiler that there are no uninitialized variables (ideally without needlessly initializing them).

### PR DESCRIPTION
**Pull request by glebm**
Tricks the compiler into skipping expensive `uninit var analysis` (`-Wmaybe-uninitialized`) by using a struct with state rather than separate variables for `best` / `bestDiff`.

This has no performance impact.

Also optimizes lookup a bit further and moves some code that does not need to be inlined to the cpp file.

```
Benchmark                                              Time             CPU      Time Old      Time New       CPU Old       CPU New
-----------------------------------------------------------------------------------------------------------------------------------
BM_GenerateBlendedLookupTable_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
BM_GenerateBlendedLookupTable_mean                  +0.0237         +0.0237       2092090       2141601       2091732       2141291
BM_GenerateBlendedLookupTable_median                +0.0237         +0.0237       2092104       2141662       2091669       2141319
BM_GenerateBlendedLookupTable_stddev                -0.6414         -0.5834           664           238           538           224
BM_GenerateBlendedLookupTable_cv                    -0.6497         -0.5930             0             0             0             0
BM_BuildTree_pvalue                                  0.0002          0.0002      U Test, Repetitions: 10 vs 10
BM_BuildTree_mean                                   +0.0410         +0.0410          4495          4679          4494          4678
BM_BuildTree_median                                 +0.0403         +0.0402          4494          4675          4493          4674
BM_BuildTree_stddev                                 +0.9515         +0.9359             7            14             7            14
BM_BuildTree_cv                                     +0.8746         +0.8596             0             0             0             0
BM_FindNearestNeighbor_pvalue                        0.0002          0.0002      U Test, Repetitions: 10 vs 10
BM_FindNearestNeighbor_mean                         -0.0399         -0.0398    1964257108    1885966812    1963954917    1885694336
BM_FindNearestNeighbor_median                       -0.0397         -0.0396    1963969748    1886074435    1963650984    1885803182
BM_FindNearestNeighbor_stddev                       -0.3380         -0.3443       1217360        805946       1225442        803469
BM_FindNearestNeighbor_cv                           -0.3105         -0.3171             0             0             0             0
OVERALL_GEOMEAN                                     +0.0077         +0.0077             0             0             0             0
```

Fixes #8135

### CODE REVIEW

File: Source/utils/palette_kd_tree.cpp [hunk 1]
```diff
@@ -0,0 +1,214 @@
...
+#include <cstddef>
+#include <cstdint>
+#include <span>
+#include <string>
+#include <utility>
+
+#ifdef USE_SDL1
+#include <SDL_video.h>
+#else
+#include <SDL_pixels.h>
```
Comment (AJenbo) [inline Source/utils/palette_kd_tree.cpp:13]: What's the benefit of importing specific SDL headers here?

Comment (glebm) [reply Source/utils/palette_kd_tree.cpp:13]: Slightly faster compilation when compiling just this one file (I've been recompiling it a lot). The benefit is minor, it's ok to change to  SDL.h

Comment (AJenbo) [reply Source/utils/palette_kd_tree.cpp:13]: Ok, good to know why it's different for this case.
