### PR TITLE
Fix DirOK for unique monsters

### LINKED ISSUE #2429: Zhar the Mad is scared and hides in subspace
Zhar the Mad is scared and hides in subspace since commit d63fcded760dc82563baa78714120f4d0cf4da13.

https://user-images.githubusercontent.com/45902449/126210760-9e6cd61e-4e9d-40e6-8a77-6129a6dd77dc.mp4

Savegame:
[zhar.zip](https://github.com/diasurgical/devilutionX/files/6843188/zhar.zip)

### PR DESCRIPTION
**Pull request by obligaron**
Fixes #2429 

Pumps Zhars courage with some mystical essence (bugfix).
But hero be prepared, I hope you can handle his mighty anger.

### CODE REVIEW

File: Source/monster.cpp [hunk 1]
```diff
@@ -4575,7 +4575,7 @@ bool DirOK(int i, Direction mdir)
 	if (monster.leaderRelation == LeaderRelation::Leashed) {
 		return futurePosition.WalkingDistance(Monsters[monster.leader].position.future) < 4;
 	}
-	if (monster._uniqtype == 0 || UniqMonst[monster._uniqtype - 1].monsterPack == UniqueMonsterPack::Leashed)
+	if (monster._uniqtype == 0 || UniqMonst[monster._uniqtype - 1].monsterPack != UniqueMonsterPack::Leashed)
 		return true;
```
Comment (AJenbo) [inline Source/monster.cpp:4579]: No unique monster is leashed, so this check marks the following code as dead code.

**Review by AJenbo — APPROVED** [review]
