### PR TITLE
Mouse/Gamepad fixes

### LINKED ISSUE #4242: [gamepad] Inventory cursor missing
Initially when utilizing the inventory the cursor can be missing or dark and stuck. This can be solved by moving the cursor. Probably replicating this may require the game to run in windowed mode and the cursor to start offscreen.

It also appears that the cursor does not snap to the first slot when opening the inventory, this may be the cause of the issue.

(this may or may not be related to the stash-gamepad branch)

### PR DESCRIPTION
**Pull request by glebm**
Introduces a `ControlDevice` global which is distinct from `ControlMode` in that it is set to `Gamepad` even when simulating a mouse.

This allows us to avoid a number of edge cases related to mode changes.

Fixes #4242

### CODE REVIEW

**Comment by glebm** [comment]
One thing I'm not sure about is whether we should call `NextMouseButtonClickEventIsSimulated` in touch.cpp

File: Source/controls/plrctrls.cpp [hunk 1]
```diff
@@ -1491,12 +1497,51 @@ bool ContinueSimulatingMouse(const SDL_Event &event, const ControllerButtonEvent
 	return false;
 }
 
+bool IsNextMouseButtonClickEventIsSimulated = false;
```
Comment (AJenbo) [inline Source/controls/plrctrls.cpp:1500]:
```suggestion
bool IsNextMouseButtonClickEventSimulated = false;

```

**Comment by AJenbo** [comment]
> One thing I'm not sure about is whether we should call `NextMouseButtonClickEventIsSimulated` in touch.cpp

I don't think so, it's not emulating the mouse in the same way i believe. I can test things out a bit later, is there something specific i should look out for?

**Comment by glebm** [comment]
@AJenbo Look out for issues around switching between mouse and touch. I suggest we merge it and fix `touch.cpp` later if needed, so that it's tested a bit more widely on master.

**Comment by AJenbo** [comment]
8 hours ago I sat down to test this, and then i started getting notifications ...

**Comment by AJenbo** [comment]
Ok, i did notice one issue when testing. When using a mouse on Android picking up and placing items in the inventory will have the mouse jump to the top and bottom of the object instead of staying in the center. But this turns out to also be an issue on master, so :shrug:

The same issue does not happen on Linux both with Hardware and Software Mouse.

**Review by AJenbo — APPROVED** [review]

**Comment by glebm** [comment]
I'm guessing that's probably an SDL issue

**Comment by AJenbo** [comment]
Probably, I just replicated it on 1.3.0 from the play store, so in any case it's non blocking :)
