### PR TITLE
Fix a few remaining C-style format in Log calls

### LINKED ISSUE #1712: Logging issues
```
VERBOSE: MPQ search paths%s
VERBOSE: Missing: %s
VERBOSE:   Found: %s in %s
VERBOSE: Missing: %s
VERBOSE: Missing: %s
VERBOSE:   Found: %s in %s
VERBOSE:   Found: %s in %s
VERBOSE: Missing: %s
VERBOSE: Missing: %s
VERBOSE:   Found: %s in %s
VERBOSE:   Found: %s in %s
VERBOSE: Missing: %s
VERBOSE: Missing: %s
VERBOSE:   Found: %s in %s
```

```
DEBUG: Unhandled SDL event: %s %d
```

### PR DESCRIPTION
**Pull request by Jmgr**
This fixes #1712.

### CODE REVIEW

File: Source/init.cpp [hunk 1]
```diff
@@ -173,7 +173,7 @@ void init_archives()
 			message.append(paths[i]);
 			message += '\'';
 		}
-		LogVerbose("MPQ search paths%s", message.c_str());
+		LogVerbose("MPQ search paths {}", message);
```
Comment (glebm) [inline Source/init.cpp:176]: This shouldn't have a space, `message` starts with a newline

Comment (Jmgr) [reply Source/init.cpp:176]: Why not `MPQ search paths:` then?

**Review by glebm — APPROVED** [review]
